param(
    [Parameter(Mandatory = $true)][string]$ClientJar,
    [string]$OutputPath = "$PSScriptRoot/../src/main/resources/font/default-widths.txt"
)

# Regenerate metrics from Mojang's vanilla 1.21.11 client, without shipping its textures.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Drawing
$archive = [IO.Compression.ZipFile]::OpenRead((Resolve-Path $ClientJar))
function Read-JsonEntry([string]$Path) {
    $reader = [IO.StreamReader]::new($archive.GetEntry($Path).Open())
    try { return $reader.ReadToEnd() | ConvertFrom-Json } finally { $reader.Dispose() }
}

try {
    $widths = @{}
    $space = Read-JsonEntry 'assets/minecraft/font/include/space.json'
    foreach ($property in $space.providers[0].advances.PSObject.Properties) {
        $widths[[char]::ConvertToUtf32($property.Name, 0)] = [int]$property.Value
    }
    $font = Read-JsonEntry 'assets/minecraft/font/include/default.json'
    foreach ($provider in $font.providers) {
        if ($provider.type -ne 'bitmap') { throw "Unexpected font provider: $($provider.type)" }
        $path = 'assets/minecraft/textures/' + $provider.file.Split(':')[1]
        $stream = $archive.GetEntry($path).Open()
        $image = [Drawing.Bitmap]::new($stream)
        try {
            $rows = @($provider.chars | ForEach-Object {
                $points = for ($index = 0; $index -lt $_.Length; $index++) {
                    [char]::ConvertToUtf32($_, $index)
                    if ([char]::IsHighSurrogate($_[$index])) { $index++ }
                }
                ,@($points)
            })
            $cellWidth = $image.Width / $rows[0].Count
            $cellHeight = $image.Height / $provider.chars.Count
            $height = if ($null -eq $provider.height) { 8 } else { $provider.height }
            for ($row = 0; $row -lt $provider.chars.Count; $row++) {
                for ($col = 0; $col -lt $rows[$row].Count; $col++) {
                    $codePoint = $rows[$row][$col]
                    if ($codePoint -eq 0 -or $widths.ContainsKey($codePoint)) { continue }
                    $right = 0
                    for ($x = 0; $x -lt $cellWidth; $x++) {
                        for ($y = 0; $y -lt $cellHeight; $y++) {
                            if ($image.GetPixel($col * $cellWidth + $x, $row * $cellHeight + $y).A -ne 0) {
                                $right = [Math]::Max($right, $x + 1)
                            }
                        }
                    }
                    # BitmapProvider rounds the scaled rightmost opaque pixel, then adds spacing.
                    $widths[$codePoint] = [int][Math]::Floor($right * $height / $cellHeight + 0.5) + 1
                }
            }
        } finally { $image.Dispose(); $stream.Dispose() }
    }
    $lines = @('# Vanilla Minecraft Java 1.21.11 default bitmap font + space provider.',
        '# Generated by tools/Extract-DefaultFontWidths.ps1 from the official client JAR.',
        '# Advance in pixels (includes character spacing) = hexadecimal Unicode code points.',
        '# Unicode fallback and resource-pack fonts are not represented here.')
    foreach ($width in ($widths.Values | Sort-Object -Unique)) {
        $points = @($widths.Keys | Where-Object { $widths[$_] -eq $width } | Sort-Object)
        $lines += "$width=" + (($points | ForEach-Object { $_.ToString('X4') }) -join ',')
    }
    New-Item -ItemType Directory -Path (Split-Path $OutputPath) -Force | Out-Null
    [IO.File]::WriteAllLines([IO.Path]::GetFullPath($OutputPath), $lines, [Text.UTF8Encoding]::new($false))
    Write-Output "Generated $($widths.Count) glyph advances."
} finally { $archive.Dispose() }
